import { Inter } from "next/font/google";

import { type Metadata } from "next";

import { QueryProvider } from "@/lib/query-client";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "MW | Modernwalk",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
